/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 girl.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'

type GLTFResult = any & {
  nodes: {
    Cube002_1: THREE.SkinnedMesh
    Cube002_2: THREE.SkinnedMesh
    Cube002_3: THREE.SkinnedMesh
    Cube002_4: THREE.SkinnedMesh
    Cube002_5: THREE.SkinnedMesh
    Cube006: THREE.Mesh
    Circle002: THREE.Mesh
    Circle003: THREE.Mesh
    copy_a: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube011: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Sphere: THREE.Mesh
    Cube001: THREE.Mesh
    Cube010: THREE.Mesh
    ctext011: THREE.Mesh
    Cube012: THREE.Mesh
    ctext010: THREE.Mesh
    Cube013: THREE.Mesh
    ctext009: THREE.Mesh
    Cube014: THREE.Mesh
    ctext008: THREE.Mesh
    Cube015: THREE.Mesh
    ctext006: THREE.Mesh
    Cube016: THREE.Mesh
    ctext004: THREE.Mesh
    Cube017: THREE.Mesh
    ctext003: THREE.Mesh
    Cube018: THREE.Mesh
    ctext002: THREE.Mesh
    Cube019: THREE.Mesh
    ctext001: THREE.Mesh
    Cube020: THREE.Mesh
    ctext: THREE.Mesh
    Cylinder003: THREE.Mesh
    Bone: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    hoodie: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Hair: THREE.MeshStandardMaterial
    pants: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    cup: THREE.MeshStandardMaterial
    Coffee_machine_material: THREE.MeshStandardMaterial
    silver: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Coffee_machine_material.001']: THREE.MeshStandardMaterial
    ['cup.003']: THREE.MeshStandardMaterial
    ['silver.001']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    wooden: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./girl.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.067, 1.41, -0.258]} scale={0.651}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.neutral_bone} />
        <skinnedMesh geometry={nodes.Cube002_1.geometry} material={materials.hoodie} skeleton={nodes.Cube002_1.skeleton} />
        <skinnedMesh geometry={nodes.Cube002_2.geometry} material={materials.Skin} skeleton={nodes.Cube002_2.skeleton} />
        <skinnedMesh geometry={nodes.Cube002_3.geometry} material={materials.Hair} skeleton={nodes.Cube002_3.skeleton} />
        <skinnedMesh geometry={nodes.Cube002_4.geometry} material={materials.pants} skeleton={nodes.Cube002_4.skeleton} />
        <skinnedMesh geometry={nodes.Cube002_5.geometry} material={materials.Material} skeleton={nodes.Cube002_5.skeleton} />
      </group>
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[0, 0.915, 0.909]} scale={[2.241, 1.096, 0.503]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials.cup} position={[-0.241, 2.302, 0.927]} rotation={[0, 0.927, -Math.PI]} scale={[-0.053, -0.139, -0.148]} />
      <mesh geometry={nodes.Circle003.geometry} material={materials.cup} position={[-0.238, 2.25, 0.929]} rotation={[0, 0.927, -Math.PI]} scale={[-0.172, -0.161, -0.172]} />
      <mesh geometry={nodes.copy_a.geometry} material={materials.cup} position={[-0.222, 3.235, 0.68]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.049, 0.027, 0.009]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Coffee_machine_material} position={[-0.329, 3.158, 1.131]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.43, 0.236, 0.466]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.silver} position={[-0.32, 2.238, 1.109]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.419, 0.02, 0.466]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Coffee_machine_material} position={[-0.329, 3.158, 1.131]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.405, 0.222, 0.44]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Coffee_machine_material} position={[-0.433, 2.613, 1.417]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.416, 0.385, 0.114]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.cup} position={[-0.094, 3.235, 0.726]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.049, 0.027, 0.009]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[-0.289, 2.282, 1.115]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={0.094} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.cup} position={[-0.339, 3.235, 0.637]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.049, 0.027, 0.009]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Coffee_machine_material.001']} position={[-0.321, 3.395, 1.103]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.028, 0.008, 0.324]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Coffee_machine_material} position={[-0.242, 2.909, 0.929]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.157, 0.026, 0.157]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['cup.003']} position={[-0.654, 3.255, 0.768]} rotation={[-Math.PI, 0.349, Math.PI / 2]} scale={[0.094, 0.034, 0.094]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['silver.001']} position={[-0.245, 2.751, 0.929]} rotation={[-Math.PI, 0.349, Math.PI / 2]} scale={[0.035, 0.119, 0.035]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['silver.001']} position={[-0.242, 2.834, 0.929]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.141, 0.052, 0.141]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.Coffee_machine_material} position={[0.045, 2.83, 1.043]} rotation={[0, -0.349, Math.PI / 2]} scale={[-0.031, -0.182, -0.031]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.547, 2.199, 0.895]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.032, 0.774, 0.275]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Coffee_machine_material} position={[-0.547, 2.176, 0.895]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.032, 0.774, 0.275]} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-0.244, 2.776, 0.93]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={0.017} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[0.054, 3.255, 0.78]} rotation={[-Math.PI, 0.349, -Math.PI]} scale={[0.049, 0.049, 0.009]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.003']} position={[1.592, 0.631, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext011.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.003']} position={[0.941, 0.631, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext010.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.003']} position={[0.29, 0.631, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext009.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.003']} position={[-0.36, 0.631, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext008.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.003']} position={[1.592, 1.308, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext006.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.003']} position={[0.941, 1.308, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext004.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.003']} position={[0.29, 1.308, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext003.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.003']} position={[-0.36, 1.308, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext002.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.003']} position={[-1.011, 1.308, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext001.geometry} material={materials.wooden} position={[-0.009, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.003']} position={[-1.661, 1.308, 1.871]} scale={[0.288, 0.288, 0.111]}>
        <mesh geometry={nodes.ctext.geometry} material={materials.wooden} position={[-0.031, -0.059, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[1.812, 4.702, 1.812]} />
      </mesh>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.004']} position={[-0.241, 2.543, 0.936]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.247, -0.007, -0.247]} />
    </group>
  )
}

useGLTF.preload('/girl.glb')
