/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 logoblend.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

type GLTFResult = any & {
  nodes: {
    Plane: THREE.Mesh
    fence001: THREE.Mesh
    fence002: THREE.Mesh
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
    build: THREE.Mesh
    door_frame: THREE.Mesh
    door_glass: THREE.Mesh
    roof: THREE.Mesh
    roof2: THREE.Mesh
    takecoffee: THREE.Mesh
    cupofcoffee: THREE.Mesh
    windows_frame: THREE.Mesh
    Circle002: THREE.Mesh
    Circle002_1: THREE.Mesh
    windows_frame001: THREE.Mesh
    build001: THREE.Mesh
    Cylinder: THREE.Mesh
    Domain: THREE.Mesh
    Circle001: THREE.Mesh
    ctext007: THREE.Mesh
  }
  materials: {
    logo: THREE.MeshStandardMaterial
    frence: THREE.MeshStandardMaterial
    ground: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    wooden: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['frence.001']: THREE.MeshStandardMaterial
    coffee_mat: THREE.MeshStandardMaterial
    smoke: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/logoblend.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.logo} position={[0, 2.693, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.fence001.geometry} material={materials.frence} position={[0, -0.107, 0]} scale={4} />
      <mesh geometry={nodes.fence002.geometry} material={materials.frence} position={[0, -0.107, 0]} scale={4} />
      <group scale={4}>
        <mesh geometry={nodes.Plane002.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.build.geometry} material={nodes.build.material} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <mesh geometry={nodes.door_frame.geometry} material={materials.wooden} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <mesh geometry={nodes.door_glass.geometry} material={materials['Material.003']} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <mesh geometry={nodes.roof.geometry} material={materials['Material.001']} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <mesh geometry={nodes.roof2.geometry} material={nodes.roof2.material} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <mesh geometry={nodes.takecoffee.geometry} material={nodes.takecoffee.material} position={[-0.11, 3.848, -1.395]} rotation={[0, 0.262, 0]} scale={0.618}>
        <mesh geometry={nodes.cupofcoffee.geometry} material={nodes.cupofcoffee.material} scale={1.096} />
      </mesh>
      <mesh geometry={nodes.windows_frame.geometry} material={materials.wooden} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <group position={[-3.124, 0.703, 3.087]} scale={0.42}>
        <mesh geometry={nodes.Circle002.geometry} material={materials['frence.001']} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.windows_frame001.geometry} material={materials['Material.003']} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <mesh geometry={nodes.build001.geometry} material={materials['Material.001']} position={[0.102, 0.22, -0.815]} scale={2.919} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.coffee_mat} position={[-0.161, 5.225, -1.413]} scale={[1.621, 0.124, 1.621]} />
      <mesh geometry={nodes.Domain.geometry} material={materials.smoke} position={[0, 4.723, -1.373]} scale={6.081} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-0.124, 5.535, -1.377]} scale={0.933} />
      <mesh geometry={nodes.ctext007.geometry} material={materials.wooden} position={[-2.334, 4.236, 0.112]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
    </group>
  )
}

useGLTF.preload('/logoblend.glb')
